aws:
  profile: upxa-user
  s3:
    bucket: upxa
    region: ap-south-1
server:
  port: ${PORT:8010}
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/uploadexa}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    root: INFO